# -*- coding: utf-8 -*-
"""
Created on Mon Mar 16 22:43:29 2026

@author: wangyunong


"""

from schnorr_signature import SchnorrSignature


schnorr = SchnorrSignature()

# Randomly generate private/public keys
private_key, public_key = schnorr.generate_keys()
"""
wrong_private_key, _ = schnorr.generate_keys()
## Wrong private key should also generated by schnorr. 
## Adapting this line would cause invalid signature.
signature = schnorr.sign(message, wrong_private_key)
"""


message = b"WELCOME TO BAOTOU"


signature = schnorr.sign(message, private_key)


valid = schnorr.verify(message, public_key, signature)

print("Private key:", private_key)
print("Public key:", public_key)
print("Signature:", signature)
print("Valid:", valid)